AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  TargetEnvr:
    Type: String
    AllowedValues:
      - dev
      - prod
  ProjectName:
    Type: String
    AllowedValues:
      - sadalsuud
      - altarf
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${ProjectName}-${TargetEnvr}
      WebsiteConfiguration:
        ErrorDocument: error.html
        IndexDocument: index.html
  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    DependsOn: [CloudFrontOriginAccessIdentity]
    Properties:
      Bucket: !Sub ${ProjectName}-${TargetEnvr}
      PolicyDocument: !Join
        - ''
        - - '{
              "Version": "2012-10-17",
              "Id": "PolicyForCloudFrontPrivateContent",
              "Statement": [
                  {
                      "Sid": "Allow-OAI-Access-To-Bucket",
                      "Effect": "Allow",
                      "Principal": {
                          "AWS": "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity '
          - !Ref CloudFrontOriginAccessIdentity
          - '" },
                      "Action": "s3:GetObject",
                      "Resource": "arn:aws:s3:::'
          - !Sub ${ProjectName}-${TargetEnvr}
          - '/*"
                  }
              ]
            }'
  CloudFrontOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub ${ProjectName}-${TargetEnvr}-OAI